### ISSUE TITLE
params with upper-case characters

### ISSUE THREAD

**Issue by Intelligent2013** [wildhaber/gohugo-amp#22]
Looks like the parameters with upper-case characters don't recognition with 'isset' function.

For example, config.toml has parameter
`googleAnalytics = "UA-12345678-123"`
But I get the message 'You must set a googleAnalytics UA-Code within the global config.toml Params.' on the page.

I've made a changes in the file themes\gohugo-amp\layouts\partials\amp\google-analytics.html:
from
`{{ if isset $.Site.Params "googleAnalytics" }}`
to
`{{ if isset $.Site.Params "googleanalytics" }}`
and everything is working now.

But the strings:
`{{ printf "%s" $.Site.Params.googleAnalytics }}`
`{{ printf "%s" $.Site.Params.googleanalytics }}`
work both.

The same problem in the file 'app-banner-header.html' and others.

**Comment by wildhaber** [comment]
@Intelligent2013 thanks for reporting this issue.

It should be fixed in the current branch `develop`. I'll make a versioned update in master as soon as its tested.

Related PR: https://github.com/wildhaber/gohugo-amp/pull/23/
