### ISSUE TITLE
Typo in the "getting started" document

### ISSUE THREAD

**Issue by Matsue** [wildhaber/gohugo-amp#27]
In https://gohugo-amp.gohugohq.com/install/ page,  ` kitchen sink` text is linked to 404 page.

Current URL: https://gohugo-amp.gohugohq.com/ktichen-sink/
Expected URL: https://gohugo-amp.gohugohq.com/kitchen-sink/

**Comment by wildhaber** [comment]
@Matsue thanks for the reporting. Just fixed 👍
