### ISSUE TITLE
add demo site to example site

### ISSUE THREAD

**Issue by dknecht** [wildhaber/gohugo-amp#28]
It would be helpful to see how you added some of the feature to demo site.  For example how you added the amp header, sidebar, and breadcrumbs.

**Comment by lucientaylor** [comment]
agreed

**Comment by abdiasriver** [comment]
isnt it?   

[demo or not](https://gohugo-amp.gohugohq.com/)

**Comment by wildhaber** [comment]
Hey there,

Actually you are totally right, for some parts it is very helpful to see the implementation details based on an example.

Therefore I made the actual repository for the demonstration publicly available at https://github.com/wildhaber/gohugo-amp.gohugohq.com 

Hope this clarifies a few open questions :-)
