### ISSUE TITLE
Using this theme with an exiting theme

### ISSUE THREAD

**Issue by InderdeepBajwa** [wildhaber/gohugo-amp#29]
GoHugo AMP is really a brilliant theme one can use. You guys are doing great job with this. However, I am currently using a theme for regular website and want to implement AMP on my website using this theme.

Since I can only use a single configuration file, I would like to request you to please help me by letting me know who can I use this theme along with a regular theme.

Thanks in advance.

**Comment by wildhaber** [comment]
There should not be a problem merging the necessary configurations from both themes into one `config.toml` file.
