### ISSUE TITLE
Dual Theme Hugo?

### ISSUE THREAD

**Issue by InderdeepBajwa** [wildhaber/gohugo-amp#31]
Hi

Since I am already using a theme that is based on Bootstrap, AMP integration isn't possible with it.
Can we use GoHugo AMP such that two themes can generate two html files (one Desktop and another Mobile) so that AMP along with normal website could be possible.

**Comment by dirk789** [comment]
I have the same question. I hope that someone knows if this is possible...

**Comment by fastzen** [comment]
Disclaimer: I've only started looking at Hugo today.

I don't know if this is helpful, Hugo can support multi-site generation:

https://discuss.gohugo.io/t/hugo-multisite-workflow/103/8

If a mobile site is hosted on a sub-domain then this workflow might provide a solution.

**Comment by InderdeepBajwa** [comment]
@dirk789  @fastzen the newly updated Hugo 0.20.2 and above renders files into a different folder, example $root/amp/ which can be used to implement AMP.
