### ISSUE TITLE
What is rm and how do I use it?

### ISSUE THREAD

**Issue by valzi** [wildhaber/gohugo-amp#37]
When installing:
```
rm -rf gohugo-amp/.git
'rm' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by MaximeSauvage1** [comment]
Hi @valzi !

"rm" is a linux command line include by default if you use Linux.
With this command you try to delete with "rm", in recursive way with option "-r" and with no validation required with "-f" (for "force"). Your target is the file ".git". Be careful with this command.

**Comment by valzi** [comment]
Thanks for explaining! I can do that in Windows. The implication is that
this project only works in Linux, since that's part of installation. Is
that true? Are there other Linux things I have to do?

**Comment by MaximeSauvage1** [comment]
There are 2 solutions:
- the equivalent of rm command on windows should be "del" (check the documentation for usage and version)
- find a tool that implement linux commands 

For this case I'll recommend you the first solution. You seems to not need usage of all the linux commands.

About the OS recommended for this project: as I'm not on it, I can't tell you if it is only runnable on Linux, sorry...

**Comment by wildhaber** [comment]
@valzi thanks for your question. This command is just there to remove the `.git` folder so you don't have any issues with submodules.

As @MaximeSauvage1 already suggested you can use `del` as a `rm` replacement or delete the `.git` folder with whatever gui you have around. In explorer, just select the folder and press `<del>`
