### ISSUE TITLE
Updating exampleSite to https://gohugo-amp.gohugohq.com/

### ISSUE THREAD

**Issue by trevorlazarus** [wildhaber/gohugo-amp#38]
Would it be possible to have the code on the exampleSite folder be updated with the documentation site's code. 

That would be really helpful to try it out.

**Comment by wildhaber** [comment]
Hey @trevorlazarus ,

Thanks for your request, actually I have made the repository from the example page publicly available at https://github.com/wildhaber/gohugo-amp.gohugohq.com

Hope this helps you further in this case :-)
